# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Build and deploy PHAR
on:
  push:
    tags:
    - "*"
jobs:
  build:
    name: Build PHAR-File
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: mbstring, intl, readline
        tools: composer:v2

    - name: Build Phar
      run: composer buildphar

    - name: Sign Phar
      env:
        DECRYPT_KEY: ${{ secrets.DECRYPT_KEY }}
        SIGN_KEY: ${{ secrets.SIGN_KEY }}
      run: |
        export GPG_TTY=$(tty)
        echo $DECRYPT_KEY
        echo Decrypting key
        gpg --batch --yes --passphrase $DECRYPT_KEY KeepAChangelogSigning.asc.gpg && gpg --batch --yes --import KeepAChangelogSigning.asc
        echo Signing Artifact
        gpg --batch --yes --pinentry-mode loopback --passphrase $SIGN_KEY -u 9A2577FF9A688FAF --armor --detach-sig build/keep-a-changelog.phar

    - name: Prepare Release-Info
      run: |
        ./bin/keep-a-changelog version:show $(echo $GITHUB_REF | cut -d / -f 3) > release.note

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*"
        bodyfile: release.note
        name: "keep-a-changelog ${{ github.event.release.tag_name }}"
        token: ${{ secrets.GITHUB_TOKEN }}
